// Package query is dinki's GraphQL metadata query layer. It resolves queries
// from the indexed metadata store (repositories, tags, manifests, blobs,
// dependents, locations, referrers) and reads image config blobs from content
// storage for history and inspect. It is read-only: deletion is always done
// by metadata mutations followed by registry garbage collection.
//
// The executor is generated by gqlgen from schema.graphql; each GraphQL type
// is bound to a model in this package whose methods resolve its fields.
package query

//go:generate go tool gqlgen generate --config gqlgen.yml

import (
	"bytes"
	"context"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/99designs/gqlgen/graphql/executor"
	"github.com/99designs/gqlgen/graphql/handler/extension"
	"github.com/99designs/gqlgen/graphql/handler/lru"
	"github.com/sysson/ocistore"
	"github.com/vektah/gqlparser/v2/ast"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

//go:embed schema.graphql
var schemaSource string

// Schema returns the GraphQL schema definition.
func Schema() string { return schemaSource }

const (
	defaultPage    = 100
	maxPage        = 1000
	maxQueryLength = 64 << 10
	maxRequestBody = 1 << 20
	maxDepth       = 16
	queryCacheSize = 256
)

// Service executes GraphQL queries against dinki metadata.
type Service struct {
	exec *executor.Executor
}

// New builds the query service over index.
func New(index *ocistore.Index) (*Service, error) {
	if index == nil {
		return nil, errors.New("query: index is required")
	}
	exec := executor.New(NewExecutableSchema(Config{Resolvers: &resolver{index: index}}))
	exec.SetQueryCache(lru.New[*ast.QueryDocument](queryCacheSize))
	exec.Use(extension.Introspection{})
	exec.Use(depthLimit(maxDepth))
	return &Service{exec: exec}, nil
}

// Exec executes a GraphQL document in-process.
// Variables may be any JSON-encodable Go values; they are normalised to the
// JSON types the executor expects.
func (s *Service) Exec(ctx context.Context, query, operationName string, variables map[string]any) *graphql.Response {
	if len(query) > maxQueryLength {
		return errorResponse(gqlerror.Errorf("query length %d exceeds the maximum of %d", len(query), maxQueryLength))
	}
	variables, err := normaliseVariables(variables)
	if err != nil {
		return errorResponse(gqlerror.Errorf("invalid variables: %v", err))
	}
	ctx = graphql.StartOperationTrace(ctx)
	now := graphql.Now()
	params := &graphql.RawParams{
		Query:         query,
		OperationName: operationName,
		Variables:     variables,
		ReadTime:      graphql.TraceTiming{Start: now, End: now},
	}
	opCtx, errs := s.exec.CreateOperationContext(ctx, params)
	if errs != nil {
		return s.exec.DispatchError(graphql.WithOperationContext(ctx, opCtx), errs)
	}
	responses, ctx := s.exec.DispatchOperation(ctx, opCtx)
	return responses(ctx)
}

func errorResponse(err *gqlerror.Error) *graphql.Response {
	return &graphql.Response{Errors: gqlerror.List{err}}
}

func normaliseVariables(variables map[string]any) (map[string]any, error) {
	if len(variables) == 0 {
		return variables, nil
	}
	data, err := json.Marshal(variables)
	if err != nil {
		return nil, err
	}
	// Numbers stay json.Number: gqlgen rejects float64 for Int arguments.
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var normalised map[string]any
	if err := decoder.Decode(&normalised); err != nil {
		return nil, err
	}
	return normalised, nil
}

// Request is a GraphQL-over-HTTP request body.
type Request struct {
	Query         string         `json:"query"`
	OperationName string         `json:"operationName,omitempty"`
	Variables     map[string]any `json:"variables,omitempty"`
}

// ServeHTTP serves GraphQL over HTTP: POST with a JSON Request body, or GET
// with query, operationName, and JSON-encoded variables parameters.
func (s *Service) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var request Request
	switch r.Method {
	case http.MethodGet:
		values := r.URL.Query()
		request.Query = values.Get("query")
		request.OperationName = values.Get("operationName")
		if raw := values.Get("variables"); raw != "" {
			decoder := json.NewDecoder(strings.NewReader(raw))
			decoder.UseNumber()
			if err := decoder.Decode(&request.Variables); err != nil {
				http.Error(w, "invalid variables", http.StatusBadRequest)
				return
			}
		}
	case http.MethodPost:
		decoder := json.NewDecoder(http.MaxBytesReader(w, r.Body, maxRequestBody))
		decoder.UseNumber()
		if err := decoder.Decode(&request); err != nil {
			http.Error(w, "invalid GraphQL request body", http.StatusBadRequest)
			return
		}
	default:
		w.Header().Set("Allow", "GET, POST")
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if strings.TrimSpace(request.Query) == "" {
		http.Error(w, "query is required", http.StatusBadRequest)
		return
	}
	response := s.Exec(r.Context(), request.Query, request.OperationName, request.Variables)
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(response)
}

// depthLimit rejects operations whose selections nest deeper than its value,
// counting fields through fragments. Fragment cycles are already rejected by
// validation, which runs first.
type depthLimit int

var _ interface {
	graphql.HandlerExtension
	graphql.OperationContextMutator
} = depthLimit(0)

func (depthLimit) ExtensionName() string                   { return "DepthLimit" }
func (depthLimit) Validate(graphql.ExecutableSchema) error { return nil }
func (d depthLimit) MutateOperationContext(_ context.Context, opCtx *graphql.OperationContext) *gqlerror.Error {
	if depth := selectionDepth(opCtx.Operation.SelectionSet); depth > int(d) {
		err := gqlerror.Errorf("query depth %d exceeds the maximum of %d", depth, int(d))
		errcode.Set(err, errcode.ValidationFailed)
		return err
	}
	return nil
}

func selectionDepth(selections ast.SelectionSet) int {
	deepest := 0
	for _, selection := range selections {
		depth := 0
		switch s := selection.(type) {
		case *ast.Field:
			depth = 1 + selectionDepth(s.SelectionSet)
		case *ast.InlineFragment:
			depth = selectionDepth(s.SelectionSet)
		case *ast.FragmentSpread:
			if s.Definition != nil {
				depth = selectionDepth(s.Definition.SelectionSet)
			}
		}
		deepest = max(deepest, depth)
	}
	return deepest
}

func limit(first *int32) (int, error) {
	if first == nil {
		return defaultPage, nil
	}
	switch {
	case *first < 1:
		return 0, errors.New("first must be positive")
	case *first > maxPage:
		return 0, fmt.Errorf("first must be at most %d", maxPage)
	}
	return int(*first), nil
}

func deref(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}
